export const ICON = {
  LOGO: "/assets/img/icon/logo.svg",
  CHECK: "/assets/img/icon/check-icon.svg",
  INPUT_CHECK: "/assets/img/icon/input-check-icon.svg",
  WORK_TYPE_REC: "/assets/img/icon/work-type-rec.svg",
  WORK_TYPE_BRANDING: "/assets/img/icon/work-type-branding.svg",
  WORK_TYPE_APP: "/assets/img/icon/work-type-app.svg",
  WORK_TYPE_WEB: "/assets/img/icon/work-type-web.svg",
  WORK_TYPE_DESIGN: "/assets/img/icon/work-type-design.svg",
  WORK_TYPE_MARKETING: "/assets/img/icon/work-type-marketing.svg",
  WORK_TYPE_TRANSLATE: "/assets/img/icon/work-type-translate.svg",
  WORK_TYPE_CONSULTING: "/assets/img/icon/work-type-consulting.svg",
  KAKAO_LOGIN: "/assets/img/icon/snsl_kakao.png",
  NAVER_LOGIN: "/assets/img/icon/snsl_naver.png",
  //
  HEADPHONE: "/assets/img/icon/headphone.png",
  CLIP: "/assets/img/icon/clip.svg",
  NOTICE: "/assets/img/icon/notice.svg",
  ARROW: "/assets/img/icon/arr.svg",
  PROFILE: "/assets/img/icon/kakao_profile.svg",
  CANCEL: "/assets/img/icon/cancel.svg",
  //
  PENCIL: "/assets/img/icon/pencil.svg",
  PAPER: "/assets/img/icon/paper.svg",
  COMMENT: "/assets/img/icon/commnet.svg",
  PUZZLE: "/assets/img/icon/puzzle.svg",
  REFERENCE: "/assets/img/icon/reference.svg",
  //
  PLUS: "/assets/img/icon/plus-icon.svg",
  BACK: "/assets/img/icon/login_image.svg",
  //
  ON_BOARDING: "/assets/img/icon/onboarding.svg",
  VIDEO_CONTENTS: "/assets/img/icon/video-contents.svg",
  PAYMENT: "/assets/img/icon/payment.svg",
  GROUP: "/assets/img/icon/group.svg",
  CART: "/assets/img/icon/cart.svg",
  LOGIN: "/assets/img/icon/login.svg",
  REGISTRATION: "/assets/img/icon/registration.svg",
  MAP: "/assets/img/icon/map.svg",
  START: "/assets/img/icon/star.svg",
  TRANSLATE: "/assets/img/icon/translate.svg",
  CLASSIFICATION: "/assets/img/icon/classification.svg",
  CLIPPINGS: "/assets/img/icon/clippings.svg",
  GPS: "/assets/img/icon/gps.svg",
  VOTE: "/assets/img/icon/vote.svg",
  ORDER: "/assets/img/icon/order.svg",
  HOME: "/assets/img/icon/home.svg",
  ALERT: "/assets/img/icon/alert.svg",
  MATCH: "/assets/img/icon/match.svg",
  TEST: "/assets/img/icon/test.svg",
  FOLLOW: "/assets/img/icon/follow.svg",
  BASIC_CONTENTS: "/assets/img/icon/basic-contents.svg",
  SEARCH: "/assets/img/icon/search.svg",
  SEARCH2: "/assets/img/icon/search2.svg",
  CHAT: "/assets/img/icon/chat.svg",
  CALL: "/assets/img/icon/call.svg",
  RESERVATION: "/assets/img/icon/reservation.svg",
  PHOTO_CONTENTS: "/assets/img/icon/photo-contents.svg",
  ETC: "/assets/img/icon/etc.svg",
  WALLET: "/assets/img/icon/wallet.svg",
  PACKAGE: "/assets/img/icon/packages.svg",
  FILE_DESCRIPTION: "/assets/img/icon/file-description.svg",
  PERSON: "/assets/img/icon/person.svg",
  CARD: "/assets/img/icon/credit-card.svg",
  PDF: "/assets/img/icon/icon_pdf1.svg",
  DOCX: "/assets/img/icon/icon_docx.svg",
  GPT: "/assets/img/icon/icon_gpt.svg",
  
  STEP1: "/assets/img/icon/step2_5.svg",
  STEP2: "/assets/img/icon/step2_4.svg",
  STEP3: "/assets/img/icon/step2_3.svg",

  LAN_KO: "/assets/img/icon/lan-ko.svg",
  RECORD: "/assets/img/icon/record.svg",
  UPLOAD_CLOUD: "/assets/img/icon/upload-cloud.svg",
  CHECK_DEFAULT: "/assets/img/icon/check-default.svg",
  FILE_DEFAULT: "/assets/img/icon/file-icon.svg",
};

export const PNG = {
  UPLOAD_EX: "/assets/img/icon/upload-ex.png",
};
