name: Server Initialize and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  initialize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Initialize Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_SERVER_IP }}
          username: ${{ secrets.NCP_SERVER_USER }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: 2222
          script: |
            sudo systemctl stop nginx || true
            sudo yum remove -y nginx || true
            sudo rm -rf /etc/nginx
            sudo rm -rf /var/www/html
            pm2 kill || true
            npm uninstall -g pm2 || true
            rm -rf ~/prometheus_final*
            
            sudo yum install -y epel-release
            sudo yum install -y nginx
            sudo yum install -y certbot python3-certbot-nginx
            
            curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
            sudo yum install -y nodejs
            
            sudo npm install -g pm2
            
            sudo mkdir -p /var/www/html
            sudo chown -R nginx:nginx /var/www/html
            
            echo 'server {
                listen 80;
                server_name app.metheus.pro;
                
                location / {
                    root   /var/www/html;
                    index  index.html index.htm;
                    try_files $uri $uri/ /index.html;
                    
                    add_header Cache-Control "no-cache, no-store, must-revalidate";
                    add_header Pragma "no-cache";
                    add_header Expires 0;
                }
            }' | sudo tee /etc/nginx/conf.d/default.conf
            
            sudo certbot --nginx -d app.metheus.pro --non-interactive --agree-tos -m admin@metheus.pro
            
            sudo firewall-cmd --permanent --add-service=http || true
            sudo firewall-cmd --permanent --add-service=https || true
            sudo firewall-cmd --reload || true

      - name: Clean and Install dependencies
        run: |
          rm -rf node_modules
          rm -rf build
          npm cache clean --force
          npm ci

      - name: Create .env file
        run: |
          echo "REACT_APP_API_ENDPOINT=https://api.metheus.pro" > .env
          echo "REACT_APP_PAGE=https://app.metheus.pro" >> .env

      - name: Build
        run: |
          REACT_APP_API_ENDPOINT=https://api.metheus.pro REACT_APP_PAGE=https://app.metheus.pro npm run build
        env:
          CI: false

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_SERVER_IP }}
          username: ${{ secrets.NCP_SERVER_USER }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: 2222
          source: "build/*"
          target: "/var/www/html"
          strip_components: 1

      - name: Final Setup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_SERVER_IP }}
          username: ${{ secrets.NCP_SERVER_USER }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: 2222
          script: |
            sudo chown -R nginx:nginx /var/www/html
            sudo systemctl restart nginx
            sudo systemctl enable nginx
            echo "=== Deployment Complete ==="
            echo "=== Checking nginx status ==="
            sudo systemctl status nginx
