name: React Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Clean npm cache
        run: npm cache clean --force
        
      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "REACT_APP_API_ENDPOINT=${{ secrets.REACT_APP_API_ENDPOINT }}" > .env
          echo "REACT_APP_PAGE=${{ secrets.REACT_APP_PAGE }}" >> .env

      - name: Build
        run: npm run build
        env:
          CI: false
          REACT_APP_API_ENDPOINT: ${{ secrets.REACT_APP_API_ENDPOINT }}
          REACT_APP_PAGE: ${{ secrets.REACT_APP_PAGE }}

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_SERVER_IP }}
          username: ${{ secrets.NCP_SERVER_USER }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: 2222
          source: "build/*"
          target: "/var/www/html"
          strip_components: 1
