name: React Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Clean and Install dependencies
        run: |
          rm -rf node_modules
          rm -rf build
          npm cache clean --force
          npm ci

      - name: Create .env file
        run: |
          echo "REACT_APP_API_ENDPOINT=https://api.metheus.pro" > .env
          echo "REACT_APP_PAGE=https://app.metheus.pro" >> .env

      - name: Build
        run: |
          REACT_APP_API_ENDPOINT=https://api.metheus.pro REACT_APP_PAGE=https://app.metheus.pro npm run build
        env:
          CI: false

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_SERVER_IP }}
          username: ${{ secrets.NCP_SERVER_USER }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: 2222
          source: "build/*"
          target: "/var/www/html"
          strip_components: 1

      - name: Restart nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_SERVER_IP }}
          username: ${{ secrets.NCP_SERVER_USER }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: 2222
          script: |
            sudo chown -R nginx:nginx /var/www/html
            sudo systemctl restart nginx
